# Generated by Django 4.1.6 on 2023-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Кратко опишите задачу', max_length=200, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('finished', 'Сделано')], default='new', help_text='Статус задачи', max_length=20, verbose_name='Статус')),
                ('execution_date', models.CharField(help_text='Введите в формате ГГГГ-ММ-ДД', max_length=10, null=True, verbose_name='Дата исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
